# Generated by Django 2.1.5 on 2019-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='energy',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
