# Generated by Django 2.1.5 on 2019-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picker', '0002_auto_20190402_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Picker.DishCategory'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Picker.IngredientCategory'),
        ),
    ]
