# Generated by Django 2.1.5 on 2019-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picker', '0004_auto_20190402_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
    ]
